site_name: "spec-weaver Spec"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
extra_javascript:
    - javascripts/custom-table-filter.js
extra_css:
    - stylesheets/extra.css
nav:
  - Home: index.md
  - AUT:
      - AUT一覧: aut.md
      - AUT-001: items/AUT-001.md
      - AUT-002: items/AUT-002.md
      - AUT-003: items/AUT-003.md
      - AUT-004: items/AUT-004.md
  - CORE:
      - CORE一覧: core.md
      - CORE-001: items/CORE-001.md
      - CORE-999: items/CORE-999.md
      - CORE-003: items/CORE-003.md
      - CORE-002: items/CORE-002.md
  - PLAN:
      - PLAN一覧: plan.md
      - PLAN-001: items/PLAN-001.md
      - PLAN-002: items/PLAN-002.md
      - PLAN-003: items/PLAN-003.md
      - PLAN-004: items/PLAN-004.md
      - PLAN-005: items/PLAN-005.md
      - PLAN-006: items/PLAN-006.md
      - PLAN-007: items/PLAN-007.md
  - QA:
      - QA一覧: qa.md
      - QA-001: items/QA-001.md
      - QA-002: items/QA-002.md
      - QA-003: items/QA-003.md
      - QA-004: items/QA-004.md
      - QA-005: items/QA-005.md
      - QA-006: items/QA-006.md
  - REQ:
      - REQ一覧: req.md
      - REQ-001: items/REQ-001.md
      - REQ-998: items/REQ-998.md
      - REQ-999: items/REQ-999.md
      - REQ-002: items/REQ-002.md
      - REQ-004: items/REQ-004.md
      - REQ-003: items/REQ-003.md
      - REQ-005: items/REQ-005.md
      - REQ-006: items/REQ-006.md
      - REQ-007: items/REQ-007.md
      - REQ-008: items/REQ-008.md
      - REQ-010: items/REQ-010.md
      - REQ-009: items/REQ-009.md
      - REQ-012: items/REQ-012.md
      - REQ-011: items/REQ-011.md
      - REQ-013: items/REQ-013.md
      - REQ-014: items/REQ-014.md
  - SPEC:
      - SPEC一覧: spec.md
      - SPEC-001: items/SPEC-001.md
  - TRC:
      - TRC一覧: trc.md
      - TRC-001: items/TRC-001.md
      - TRC-002: items/TRC-002.md
      - TRC-003: items/TRC-003.md
      - TRC-004: items/TRC-004.md
  - VIS:
      - VIS一覧: vis.md
      - VIS-001: items/VIS-001.md
      - VIS-002: items/VIS-002.md
      - VIS-003: items/VIS-003.md
      - VIS-004: items/VIS-004.md
      - VIS-005: items/VIS-005.md
      - VIS-006: items/VIS-006.md
      - VIS-007: items/VIS-007.md
      - VIS-008: items/VIS-008.md

  - 振る舞い仕様 (Features):
      - features/index.md

markdown_extensions:
  - tables
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
